## SPDX-FileCopyrightText: 2022 Winni Neessen <wn@neessen.dev>
##
## SPDX-License-Identifier: MIT

[run]
go = "1.20"
tests = true

[linters]
enable = ["stylecheck", "whitespace", "containedctx", "contextcheck", "decorder",
    "errname", "errorlint", "gofmt", "gofumpt", "goimports"]

[linters-settings.goimports]
local-prefixes = "github.com/wneessen/niljson"
